### PR TITLE
update environment for pinned holoviz tools

### PR DESCRIPTION
**Pull request by kcpevey**
* use holoviews, hvplot, and ibis-framework from `qoansight/label/omnisci` channel
* add several related packages

Note: 
- This works for `notebooks/workshop/Connecting_Holoviz...*.ipynb` and `notebooks/workshop/Interactive_Computing....*ipynb` (the holoviews and basic demo notebooks, respectively)
- This does not work for `notebooks/workshop/Altair...ipynb`
  - Throws `Javascript Error: Unexpected token < in JSON at position 0`
- This does not work for `notebooks/workshop/User_Defined_Algorithms....ipynb`
  - Requires `rbc>0.4`, this provides `0.2.2`

### CODE REVIEW

**Comment by anirrudh** [comment]
Looking into this issue

**Comment by anirrudh** [comment]
cc: @xmnlab

**Comment by dharhas** [comment]
So why are we pinned to 0.2.2? Which example needs that?

**Comment by kcpevey** [comment]
its resolving to 0.2.2, but I don't know what in the stack is pinning it back

**Pull request closed without merging**
